spring:
  application:
    name: Auth
  datasource:
    url: jdbc:postgresql://localhost:5432/Event-Scheduling-and-RSVP-Platform
    username: postgres
    password: Sakkireddy@1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect